---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint
  options:
    config-file: molecule/shared/.yaml_lint.yml

platforms:
  # https://app.vagrantup.com/boxes/search?provider=virtualbox
  - name: v-centos7
    box: centos/7
    interfaces:
      - network_name: private_network
        type: static
        auto_config: true
        ip: 192.168.90.205
    provider_options:
      memory: 1024
      cpus: 1
    groups:
      - centos

  - name: v-ubuntu1604
    # box: ubuntu/xenial64
    box: bento/ubuntu-16.04
    interfaces:
      - network_name: private_network
        type: static
        auto_config: true
        ip: 192.168.90.206
    provider_options:
      memory: 1024
      cpus: 1
    groups:
      - ubuntu
      - python3

  - name: v-ubuntu1404
    box: ubuntu/trusty64
    interfaces:
      - network_name: private_network
        type: static
        auto_config: true
        ip: 192.168.90.207
    provider_options:
      memory: 1024
      cpus: 1
    groups:
      - ubuntu

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - verify
    - destroy

verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
